FROM ruby:3.2.3

WORKDIR /direct_servers

RUN apt-get update -qq && \
    apt-get upgrade -y

RUN gem install redis
RUN gem install jwt
RUN gem install oj

COPY ./direct_servers .

WORKDIR /direct_servers/session

CMD [ "ruby", "server.rb" ]