FROM ruby:3.2.3

WORKDIR /mo_session

RUN apt-get update -qq && \
    apt-get upgrade -y

RUN gem install redis
RUN gem install jwt
RUN gem install oj

COPY ./direct_servers/mo_session .

CMD [ "ruby", "server.rb" ]