FROM ruby:3.2.3

WORKDIR /api

RUN apt-get update -qq && \
    apt-get upgrade -y && \
    apt-get install -y sudo build-essential libpq-dev postgresql-contrib

COPY Gemfile .
COPY Gemfile.lock .

RUN bundle install

COPY ./docker/entrypoints/* /usr/local/bin/

RUN chmod +x /usr/local/bin/*

COPY . .

ENTRYPOINT [ "production.sh" ]

CMD [ "rails", "server", "-e", "production", "-b", "0.0.0.0", "-p", "3000" ]