default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV["MO_DATABASE_USERNAME"] %>
  password: <%= ENV["MO_DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mo_development

test:
  <<: *default
  database: mo_test
#
production:
  primary: &primary_production
    <<: *default
    database: mo_production
    username: <%= ENV["MO_DATABASE_USERNAME"] %>
    password: <%= ENV["MO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: mo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mo_production_cable
    migrations_paths: db/cable_migrate
